# Touchpad Gestures

gesture = 3, horizontal, workspace
gesture = 3, up, dispatcher, togglespecialworkspace
gesture = 3, down, dispatcher, togglespecialworkspace

gesture = 4, up, fullscreen
gesture = 4, down, fullscreen
gesture = 4, right, float
gesture = 4, left, float
